version: '3.8'

services:
  db:
    image: postgres
    ports:
      - "5436:5432"
    environment:
      POSTGRES_PASSWORD: password
    restart: always

volumes:
  postgres_data:

#  docker run --name database -e POSTGRES_PASSWORD=password -d -p 5436:5432 postgres